spring:
  application:
    name: employeemanagement
  datasource:
    url: jdbc:postgresql://localhost:5432/empsystem
    password: welcome
    username: postgres
  jpa:
    properties:
      hibernate :
        dialect : org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update